'use strict';

// Bundles src/core/*.js and server/rooms.js into client/core.bundle.js: each
// CommonJS module is wrapped in a function and linked by a tiny require(),
// exposed to the page as window.TetrisCore. A classic <script> works from
// file://, so the hot-seat client can be opened by double-clicking
// client/index.html with no server. Online play is peer-to-peer: the room
// creator's browser runs server/rooms.js itself. The game server
// (server/index.js) also calls build() on startup.

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const srcDir = path.join(root, 'src', 'core');
const roomsFile = path.join(root, 'server', 'rooms.js');
const outFile = path.join(root, 'client', 'core.bundle.js');

function wrap(file) {
  const name = path.basename(file, '.js');
  const code = fs.readFileSync(file, 'utf8');
  return `defs[${JSON.stringify(name)}] = function (module, exports, require) {\n${code}\n};`;
}

function build({ quiet = false } = {}) {
  const files = fs
    .readdirSync(srcDir)
    .filter((f) => f.endsWith('.js'))
    .sort()
    .map((f) => path.join(srcDir, f));
  const modules = [...files, roomsFile].map(wrap);

  const bundle = `// Generated by scripts/build-client.js from src/core. Do not edit.
(function () {
  const defs = {};
  const cache = {};
  function load(request) {
    const name = request.replace(/^.*\\//, '').replace(/\\.js$/, '');
    if (cache[name]) return cache[name].exports;
    if (!defs[name]) throw new Error('Unknown core module: ' + request);
    const module = { exports: {} };
    cache[name] = module;
    defs[name](module, module.exports, load);
    return module.exports;
  }

${modules.join('\n\n')}

  window.TetrisCore = {
    constants: load('constants'),
    pieces: load('pieces'),
    board: load('board'),
    game: load('game'),
    bot: load('bot'),
    invariants: load('invariants'),
    rooms: load('rooms'),
  };
})();
`;

  fs.writeFileSync(outFile, bundle);
  if (!quiet) {
    console.log(`Built ${path.relative(root, outFile)}`);
    console.log(`Open ${path.join(root, 'client', 'index.html')} in a browser.`);
  }
}

if (require.main === module) build();

module.exports = { build };
