'use strict';

// Bundles src/core/*.js into client/core.bundle.js: each CommonJS module is
// wrapped in a function and linked by a tiny require(), exposed to the page as
// window.TetrisCore. A classic <script> works from file://, so the hot-seat
// client can be opened by double-clicking client/index.html with no server.
// The game server (server/index.js) also calls build() on startup.

const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const srcDir = path.join(root, 'src', 'core');
const outFile = path.join(root, 'client', 'core.bundle.js');

function build({ quiet = false } = {}) {
  const modules = fs
    .readdirSync(srcDir)
    .filter((f) => f.endsWith('.js'))
    .sort()
    .map((f) => {
      const name = path.basename(f, '.js');
      const code = fs.readFileSync(path.join(srcDir, f), 'utf8');
      return `defs[${JSON.stringify(name)}] = function (module, exports, require) {\n${code}\n};`;
    });

  const bundle = `// Generated by scripts/build-client.js from src/core. Do not edit.
(function () {
  const defs = {};
  const cache = {};
  function load(request) {
    const name = request.replace(/^\\.\\//, '').replace(/\\.js$/, '');
    if (cache[name]) return cache[name].exports;
    if (!defs[name]) throw new Error('Unknown core module: ' + request);
    const module = { exports: {} };
    cache[name] = module;
    defs[name](module, module.exports, load);
    return module.exports;
  }

${modules.join('\n\n')}

  window.TetrisCore = {
    constants: load('constants'),
    pieces: load('pieces'),
    board: load('board'),
    game: load('game'),
    invariants: load('invariants'),
  };
})();
`;

  fs.writeFileSync(outFile, bundle);
  if (!quiet) {
    console.log(`Built ${path.relative(root, outFile)}`);
    console.log(`Open ${path.join(root, 'client', 'index.html')} in a browser.`);
  }
}

if (require.main === module) build();

module.exports = { build };
